### ISSUE TITLE
Create and Read-many endpoints for Threads 

### ISSUE THREAD

**Issue by Semuca** [Semuca/CITS3403#7]
### Overview
This is to be implemented for the 'Trade Forum' page
The database will contain: 
- Title
- Description
- UserID
- Created at

Endpoints:
POST/threads
GET/threads

### For this issue to be completed
- [x] The backend should have a database that stores all thread #17 
- [x] The backend should have an endpoint to create a new thread #22 
- [x] The backend should have an endpoint to read many threads #22
